name    'riofs'
version '0.0.1'
source 'UNKNOWN'
author 'Nicolas Boisselier'
license 'GNU General Public License, Version 3+'
summary 'UNKNOWN'
description 'Install riofs from source'
project_page 'https://github.com/nboisselier/puppet-riofs'
